apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: notifications-service
  namespace: camunda
spec:
  selector:
    matchLabels:
      app: notifications
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notif
        image: notif:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 9002