apiVersion: v1
kind: Pod
metadata:
  name: notification-service
  labels:
    name: notification-service
spec:
  containers:
  - name: notification-service
    image: adlahd/notify
    imagePullPolicy: Never
    resources:
      limits:
        memory: "8Mi"
        cpu: "125m"
    ports:
      - containerPort: 9002