apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: refund-service
  namespace: camunda
spec:
  selector:
    matchLabels:
      app: refund
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: refund
    spec:
      containers:
      - name: refund
        image: refund:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 9003