apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: fetch-cr-service
  namespace: camunda
spec:
  selector:
    matchLabels:
      app: fetch-cr
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: fetch-cr
    spec:
      containers:
      - name: cr
        image: cr:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 9000