apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: eligibility-service
  namespace: camunda
spec:
  selector:
    matchLabels:
      app: eligibility
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: eligibility
    spec:
      containers:
      - name: elig
        image: elig:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 9001